#+TITLE: Git repository examples
#+AUTHOR: Daniel Persson

This repo contains example repositories to be used with [[https://github.com/kh31d4r/git-demo-tools][Git Demo Tools]].

- =unmerged= Contains dummy commits on the master branch and an
  unmerged feature branch. Intended to be used to show the difference
  between fast-forward, merge and rebase.

- =references= Contains dummy commits on a merged branch and on
  master. A tag also exists, and the tagged commit has a distinct name
  enough to use for =:/= syntax referencing;

- =rebase= Contains a single file in a single branch, with some
  commits that adds easily trace:able content. It also contains a
  makefile which fails in one commit, to be able to show exec.

- =bisect= Contains a makefile that takes 10s to run, at some point it
  used to take 5s. To find the culprit commit:
  #+BEGIN_SRC sh
    git bisect start
    git bisect bad         # default is HEAD
    git bisect good v2.0.0 # the last release
    git bisect run timeout 7 make
  #+END_SRC

- =bisect-mini= Contains only 32 commits, to fit the whole history on
  the screen at once, and the build takes twice as long, to allow for
  commentary while the bisect runs (make sure to increase timeout to
  12s).
